# Generated by Django 4.2.1 on 2023-08-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='student_name',
        ),
    ]
